require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

platform :ios, '11.0'

target 'ZoomApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  target 'ZoomAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ZoomApp-tvOS' do
  # Pods for ZoomApp-tvOS

  target 'ZoomApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
